version: '3'
services:
  frontend:
    image: mustapha69/front_tunisairmob2:${BUILD_ID}  # changed to lowercase
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  backend:
    image: mustapha69/back_tunisairmob2:${BUILD_ID}  # changed to lowercase
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=production
